#!/usr/bin/env python3
"""Generate SUPPORT.md from test results and conformance reports.

Standing discipline #3: the support matrix is a build artifact,
never hand-written. A hand-written matrix ends up carrying the disclaimer "when
this table and the code disagree, the code wins" -- so automate it and they
cannot disagree.

  usage: python tools/gen_support_matrix.py --junit r.xml --conform cpu.json [gpu.json ...]
"""
from __future__ import annotations

import argparse, collections, datetime, json, pathlib, sys
import xml.etree.ElementTree as ET

RESULT_MARK = {"pass": "yes", "unsupported": "n/a", "skip": "?", "fail": "FAIL"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--junit", type=pathlib.Path)
    ap.add_argument("--conform", type=pathlib.Path, nargs="*", default=[])
    ap.add_argument("--out", type=pathlib.Path, default=pathlib.Path("SUPPORT.md"))
    a = ap.parse_args()

    L: list[str] = ["# Support matrix", "",
                    "**Generated by `tools/gen_support_matrix.py` — do not edit.**", ""]
    L.append(f"Produced {datetime.datetime.now(datetime.timezone.utc):%Y-%m-%d %H:%M UTC}.")
    L.append("")

    if a.junit and a.junit.exists():
        root = ET.parse(a.junit).getroot()
        cases = root.iter("testcase")
        by_tier: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
        for c in cases:
            f = c.get("classname", "")
            tier = ("tier0" if "tier0" in f else "tier1" if "tier1" in f
                    else "tier2" if "tier2" in f else "other")
            if c.find("failure") is not None or c.find("error") is not None:
                by_tier[tier]["fail"] += 1
            elif c.find("skipped") is not None:
                by_tier[tier]["skip"] += 1
            else:
                by_tier[tier]["pass"] += 1
        L += ["## Tests", "", "| tier | pass | skip | fail |", "|---|---:|---:|---:|"]
        for t in sorted(by_tier):
            c = by_tier[t]
            L.append(f"| {t} | {c['pass']} | {c['skip']} | {c['fail']} |")
        L.append("")

    reports = []
    for p in a.conform:
        if p.exists():
            reports.append(json.loads(p.read_text()))
    if reports:
        L += ["## Capabilities by plugin", "",
              "`yes` = works · `n/a` = plugin does not offer it · `?` = untested · "
              "`FAIL` = defect", ""]
        names = [r["plugin"] for r in reports]
        L.append("| check | " + " | ".join(names) + " |")
        L.append("|---|" + "---|" * len(names))
        maps = [{c["id"]: c["result"] for c in r["checks"]} for r in reports]
        for cid in sorted({k for m in maps for k in m}):
            L.append(f"| `{cid}` | "
                     + " | ".join(RESULT_MARK.get(m.get(cid, "skip"), "?") for m in maps) + " |")
        L += ["", "## Plugins", "", "| plugin | PJRT API | headers | slots | extensions |",
              "|---|---|---|---:|---|"]
        for r in reports:
            ext = ", ".join(e["name"] or f"type{e['type']}" for e in r["extensions"]) or "none"
            L.append(f"| {r['plugin']} | {r['api_version'][0]}.{r['api_version'][1]} | "
                     f"{r['abi_version'][0]}.{r['abi_version'][1]} | {r['slots']} | {ext} |")
        L.append("")

    a.out.write_text("\n".join(L))
    print(f"wrote {a.out} ({len(L)} lines, {len(reports)} plugin report(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
