#!/usr/bin/env python3
"""Generate pypjrt's ABI module from the vendored OpenXLA C headers.

Ground truth is libclang's own record layout — no offset is ever computed by
hand. The emitted module additionally carries clang's offsets and
sizes as *assertions* against ctypes' independently-computed layout, so any
divergence fails loudly at import instead of corrupting memory at runtime.

  usage:  python tools/gen_abi.py [--vendor DIR] [--out DIR]
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

import clang.cindex as CX


def builtin_includes() -> list[str]:
    """Where clang's *own* headers live (stdbool.h, stdint.h, ...).

    The `libclang` wheel ships the shared library but none of these, so they
    must come from an installed clang -- and it has to be a *matching* one.
    Feeding one LLVM's builtin headers to another LLVM's libclang does not
    fail cleanly: on a runner carrying several toolchains it parsed far enough
    to resolve `stdbool.h` and then reported `unknown type name 'int64_t'`.
    So: ask a clang binary for its own resource dir, and only if that is
    unavailable fall back to the *newest* directory that really has the
    headers -- never a blend of several.
    """
    env = os.environ.get("PYPJRT_CLANG_INCLUDE")
    if env:
        return [p for p in env.split(os.pathsep) if p]

    for exe in ("clang", "clang-18", "clang-17", "clang-16"):
        try:
            out = subprocess.run([exe, "-print-resource-dir"], capture_output=True,
                                 text=True, timeout=30)
        except (OSError, subprocess.SubprocessError):
            continue
        if out.returncode == 0:
            inc = Path(out.stdout.strip()) / "include"
            if (inc / "stdint.h").is_file():
                return [str(inc)]

    cands = [p for p in Path("/usr/lib").glob("llvm-*/lib/clang/*/include")
             if (p / "stdint.h").is_file()]
    cands += [p for p in Path("/usr/lib").glob("clang/*/include")
              if (p / "stdint.h").is_file()]
    # Version-aware sort: plain string order puts llvm-14 ahead of llvm-18.
    def key(p: Path) -> list[int]:
        return [int(n) for n in re.findall(r"\d+", str(p))]
    return [str(max(cands, key=key))] if cands else []

# ---------------------------------------------------------------------------

CTYPE_BY_KIND = {
    CX.TypeKind.BOOL: "ctypes.c_bool",
    CX.TypeKind.CHAR_S: "ctypes.c_char",
    CX.TypeKind.SCHAR: "ctypes.c_int8",
    CX.TypeKind.UCHAR: "ctypes.c_uint8",
    CX.TypeKind.SHORT: "ctypes.c_int16",
    CX.TypeKind.USHORT: "ctypes.c_uint16",
    CX.TypeKind.INT: "ctypes.c_int32",
    CX.TypeKind.UINT: "ctypes.c_uint32",
    CX.TypeKind.LONG: "ctypes.c_long",
    CX.TypeKind.ULONG: "ctypes.c_ulong",
    CX.TypeKind.LONGLONG: "ctypes.c_int64",
    CX.TypeKind.ULONGLONG: "ctypes.c_uint64",
    CX.TypeKind.FLOAT: "ctypes.c_float",
    CX.TypeKind.DOUBLE: "ctypes.c_double",
}

# Every pointer is opaque to us: we hold addresses, never dereference through
# ctypes' pointer machinery. c_void_p keeps the layout right and the API honest.
POINTERISH = {CX.TypeKind.POINTER, CX.TypeKind.FUNCTIONPROTO,
              CX.TypeKind.FUNCTIONNOPROTO, CX.TypeKind.INCOMPLETEARRAY}

HEADER = '''\
# AUTO-GENERATED by tools/gen_abi.py -- DO NOT EDIT.
#
# Source: vendored OpenXLA headers, PJRT {pjrt_major}.{pjrt_minor}, XLA FFI {ffi_major}.{ffi_minor}.
# Layout ground truth is libclang; the asserts below check ctypes agrees.
from __future__ import annotations

import ctypes

PJRT_API_MAJOR = {pjrt_major}
PJRT_API_MINOR = {pjrt_minor}
XLA_FFI_API_MAJOR = {ffi_major}
XLA_FFI_API_MINOR = {ffi_minor}

# PJRT_Api layout: struct_size, extension_start, pjrt_api_version, then the
# function-pointer table. Slot index == declaration order.
VTABLE_OFFSET = {vtable_offset}
SLOT = {{
{slots}}}
FUNCTIONS = tuple(SLOT)
'''


def canonical(t: CX.Type) -> CX.Type:
    return t.get_canonical()


def ctype_expr(t: CX.Type, known: set[str]) -> str:
    """Map a clang type to a ctypes expression."""
    c = canonical(t)
    if c.kind in POINTERISH:
        return "ctypes.c_void_p"
    if c.kind is CX.TypeKind.ENUM:
        # clang tells us the promoted integer type an enum actually occupies
        decl = c.get_declaration()
        it = decl.enum_type
        return CTYPE_BY_KIND.get(it.kind, "ctypes.c_int32")
    if c.kind in CTYPE_BY_KIND:
        return CTYPE_BY_KIND[c.kind]
    if c.kind is CX.TypeKind.CONSTANTARRAY:
        inner = ctype_expr(c.element_type, known)
        return f"({inner} * {c.element_count})"
    if c.kind in (CX.TypeKind.RECORD, CX.TypeKind.ELABORATED):
        decl = c.get_declaration()
        name = known.get(decl.get_usr())
        if name:
            return name
        name = decl.spelling
        # An opaque/undeclared record can only appear behind a pointer, which we
        # already handled; anything else means the generator is out of date.
        raise NotImplementedError(f"unknown record type {name!r} ({c.kind})")
    raise NotImplementedError(f"unmapped type {c.spelling!r} ({c.kind})")


_VALID = re.compile(r"^[A-Za-z_]\w*$")


class Record:
    def __init__(self, cursor: CX.Cursor, pyname: str):
        self.cursor = cursor
        self.name: str = pyname
        self.cname: str = cursor.spelling
        self.is_union = cursor.kind is CX.CursorKind.UNION_DECL
        # A truly anonymous union/struct member has NO FIELD_DECL -- clang emits
        # it as a bare {STRUCT,UNION}_DECL child. Dropping it silently shifts
        # every following field, which is what the generated _check caught in
        # PJRT_Buffer_MemoryLayout. Treat anonymous record children as members.
        self.fields: list[CX.Cursor] = []
        for ch in cursor.get_children():
            if ch.kind is CX.CursorKind.FIELD_DECL:
                self.fields.append(ch)
            elif (ch.kind in (CX.CursorKind.STRUCT_DECL, CX.CursorKind.UNION_DECL)
                  and ch.is_definition() and not _VALID.match(ch.spelling or "")):
                self.fields.append(ch)

    def deps(self, known: dict[str, str]) -> set[str]:
        out: set[str] = set()
        for f in self.fields:
            c = canonical(f.type)
            if c.kind is CX.TypeKind.CONSTANTARRAY:
                c = canonical(c.element_type)
            if c.kind is CX.TypeKind.RECORD:
                n = known.get(c.get_declaration().get_usr())
                if n and n != self.name:
                    out.add(n)
        return out


def collect(tu: CX.TranslationUnit, vendor: Path):
    records: dict[str, Record] = {}
    enums: dict[str, list[tuple[str, int]]] = {}
    vendor_s = str(vendor.resolve())

    def in_vendor(cur: CX.Cursor) -> bool:
        f = cur.location.file
        return bool(f) and str(Path(f.name).resolve()).startswith(vendor_s)

    anon = 0
    for cur in tu.cursor.walk_preorder():
        if not in_vendor(cur):
            continue
        if cur.kind in (CX.CursorKind.STRUCT_DECL, CX.CursorKind.UNION_DECL):
            if not cur.is_definition():
                continue
            usr = cur.get_usr()
            if usr in records:
                continue
            if _VALID.match(cur.spelling or ""):
                pyname = cur.spelling
            else:
                anon += 1
                pyname = f"_Anon{anon}"
            records[usr] = Record(cur, pyname)
        elif cur.kind is CX.CursorKind.ENUM_DECL and cur.is_definition():
            vals = [(c.spelling, c.enum_value) for c in cur.get_children()]
            # Anonymous enums still carry their constants; key them by first name.
            # clang does not spell them "": it says "(unnamed enum at
            # /abs/path.h:100:1)", which is truthy and *absolute*, so taking it
            # verbatim bakes the generating machine's paths into the committed
            # module and the reproducibility check fails on any other checkout.
            # Same _VALID guard the record path above already applies.
            spelled = cur.spelling or ""
            key = spelled if _VALID.match(spelled) else (vals[0][0] if vals else "")
            if key and vals:
                enums.setdefault(key, vals)
    return records, enums


def struct_size_map(vendor: Path) -> dict[str, str]:
    """PJRT_DEFINE_STRUCT_TRAITS(Type, last_field) -> {Type: last_field}.

    PJRT's convention is STRUCT_SIZE == offsetof(last) + sizeof(last), which is
    NOT sizeof(struct) whenever the struct ends in a narrow field. Getting this
    wrong makes the plugin reject the call.
    """
    out: dict[str, str] = {}
    pat = re.compile(
        r"(?:PJRT|XLA_FFI)_DEFINE_STRUCT_TRAITS\(\s*([A-Za-z_]\w*)\s*,\s*([A-Za-z_]\w*)\s*\)",
        re.S,
    )
    for h in sorted(vendor.rglob("*.h")):
        for m in pat.finditer(h.read_text(errors="replace")):
            out[m.group(1)] = m.group(2)
    return out


PROTO_MESSAGES = ("CompileOptionsProto", "ExecutableBuildOptionsProto")


def proto_fields(vendor: Path) -> dict[str, dict[str, int]]:
    """Field numbers for the messages we encode by hand.

    Hand-typing these is how you end up publishing `use_spmd_partitioning = 7` (it is
    6; 7 is use_auto_spmd_partitioning) and `use_shardy_partitioner = 34` (it is
    19) -- numbers lifted from the wrong message in xla.proto. Generate them.
    """
    src = (vendor / "xla/pjrt/proto/compile_options.proto").read_text()
    out: dict[str, dict[str, int]] = {}
    for msg in PROTO_MESSAGES:
        m = re.search(rf"^message {msg} \{{(.*?)^\}}", src, re.S | re.M)
        if not m:
            continue
        fields: dict[str, int] = {}
        for fm in re.finditer(
            r"^\s*(?:optional\s+|repeated\s+)?[\w.<>, ]+?\s+(\w+)\s*=\s*(\d+)\s*;",
            m.group(1), re.M,
        ):
            fields[fm.group(1)] = int(fm.group(2))
        out[msg] = fields
    return out


def emit_record(r: Record, known: dict[str, str], sizes: dict[str, str]) -> str:
    lines: list[str] = []
    base = "ctypes.Union" if r.is_union else "ctypes.Structure"

    # An anonymous union/struct *member* still occupies space. Dropping it
    # silently shifts every following field -- the generated _check caught
    # exactly that in PJRT_Buffer_MemoryLayout. Give it a synthetic name and
    # splice its members via ctypes' _anonymous_.
    names: list[str] = []
    anon_names: list[str] = []
    for i, f in enumerate(r.fields):
        if f.kind is CX.CursorKind.FIELD_DECL and f.spelling:
            names.append(f.spelling)
        else:
            n = f"_anon{i}"
            names.append(n)
            anon_names.append(n)

    lines.append(f"class {r.name}({base}):")
    if anon_names:
        # _anonymous_ must be assigned before _fields_
        lines.append(f"    _anonymous_ = {tuple(anon_names)!r}")
    lines.append("    _fields_ = [")
    for n, f in zip(names, r.fields):
        lines.append(f"        ({n!r}, {ctype_expr(f.type, known)}),")
    lines.append("    ]")
    lines.append("")

    # clang's ground truth, asserted against ctypes' own computation
    checks: list[str] = []
    for n, f in zip(names, r.fields):
        if f.kind is not CX.CursorKind.FIELD_DECL or not f.spelling:
            continue  # unnamed member: clang has no offset to look up by name
        off = r.cursor.type.get_offset(f.spelling)
        if off < 0:  # clang could not lay it out
            continue
        checks.append(f"    ({n!r}, {off // 8}),")
    if checks:
        lines.append(f"_OFFSETS_{r.name} = (")
        lines += checks
        lines.append(")")
        lines.append(f"_check(({r.name}), _OFFSETS_{r.name}, {r.cursor.type.get_size()})")

    last = sizes.get(r.cname)
    if last:
        off = r.cursor.type.get_offset(last)
        fld = next((x for x in r.fields if x.spelling == last), None)
        if off >= 0 and fld is not None:
            total = off // 8 + fld.type.get_size()
            lines.append(f"{r.name}_STRUCT_SIZE = {total}  # offsetof({last}) + sizeof({last})")
    lines.append("")
    return "\n".join(lines)


def toposort(by_name: dict[str, Record], known: dict[str, str]) -> list[Record]:
    out: list[Record] = []
    seen: set[str] = set()
    temp: set[str] = set()

    def visit(name: str):
        if name in seen or name not in by_name:
            return
        if name in temp:
            return  # cycle: only reachable through pointers, which are opaque
        temp.add(name)
        for d in sorted(by_name[name].deps(known)):
            visit(d)
        temp.discard(name)
        seen.add(name)
        out.append(by_name[name])

    for n in sorted(by_name):
        visit(n)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vendor", default="vendor", type=Path)
    ap.add_argument("--out", default="src/pypjrt/_abi", type=Path)
    args = ap.parse_args()

    vendor: Path = args.vendor.resolve()
    hdr = vendor / "xla/pjrt/c/pjrt_c_api.h"
    ffi_hdr = vendor / "xla/ffi/api/c_api.h"

    def macro(path: Path, name: str) -> int:
        m = re.search(rf"^#define {name} (\d+)", path.read_text(), re.M)
        assert m, f"{name} not found in {path}"
        return int(m.group(1))

    pj_major, pj_minor = macro(hdr, "PJRT_API_MAJOR"), macro(hdr, "PJRT_API_MINOR")
    ffi_major, ffi_minor = macro(ffi_hdr, "XLA_FFI_API_MAJOR"), macro(ffi_hdr, "XLA_FFI_API_MINOR")

    index = CX.Index.create()
    # One TU including both headers, so FFI and PJRT records land together.
    shim = vendor / "_gen_shim.c"
    # Extension headers are NOT transitively included by pjrt_c_api.h, so a shim
    # that includes only the core silently omits every extension struct -- which
    # is how PJRT_Client_RuntimeAbiVersion_Args went missing. Include them all.
    includes = ['#include "xla/pjrt/c/pjrt_c_api.h"', '#include "xla/ffi/api/c_api.h"']
    for h in sorted((vendor / "xla/pjrt/c").glob("*.h")):
        rel = h.relative_to(vendor).as_posix()
        if rel not in ("xla/pjrt/c/pjrt_c_api.h",):
            includes.append(f'#include "{rel}"')
    shim.write_text("\n".join(includes) + "\n")
    try:
        # Parsed as C++: some extension headers (collectives) use C++ tag-less
        # type references. Layout of these POD C-ABI structs is identical, and
        # the generated _check plus the pinned spike constants prove it.
        cflags = ["-I", str(vendor), "-x", "c++", "-std=c++17"]
        builtins = builtin_includes()
        if not builtins:
            print("gen_abi: found no clang builtin headers (stdint.h, stdbool.h). "
                  "Install a clang matching the libclang in use, or set "
                  "PYPJRT_CLANG_INCLUDE to its resource include dir.", file=sys.stderr)
            return 1
        for cand in builtins:
            cflags += ["-isystem", cand]
        tu = index.parse(str(shim), args=cflags)
        diags = [d for d in tu.diagnostics if d.severity >= CX.Diagnostic.Error]
        if diags:
            for d in diags[:10]:
                print(f"clang: {d.spelling} at {d.location}", file=sys.stderr)
            return 1

        by_usr, enums = collect(tu, vendor)
        sizes = struct_size_map(vendor)
        known = {usr: r.name for usr, r in by_usr.items()}
        records = {r.name: r for r in by_usr.values()}

        api = records.get("PJRT_Api")
        assert api is not None, "PJRT_Api not found"
        fn_fields = [f for f in api.fields
                     if canonical(f.type).kind in POINTERISH and f.spelling.startswith("PJRT_")]
        vtable_off = api.cursor.type.get_offset(fn_fields[0].spelling) // 8
        slots = "".join(f"    {f.spelling!r}: {i},\n" for i, f in enumerate(fn_fields))

        args.out.mkdir(parents=True, exist_ok=True)
        mod = args.out / f"pjrt_{pj_major}_{pj_minor}.py"

        body = [HEADER.format(pjrt_major=pj_major, pjrt_minor=pj_minor,
                              ffi_major=ffi_major, ffi_minor=ffi_minor,
                              vtable_offset=vtable_off, slots=slots)]
        body.append('''
def _check(cls, offsets, clang_size):
    """Assert ctypes' independently-computed layout matches clang's."""
    for name, want in offsets:
        got = getattr(cls, name).offset
        if got != want:
            raise AssertionError(
                f"{cls.__name__}.{name}: ctypes offset {got} != clang {want}")
    if ctypes.sizeof(cls) != clang_size:
        raise AssertionError(
            f"sizeof({cls.__name__}): ctypes {ctypes.sizeof(cls)} != clang {clang_size}")

''')

        pf = proto_fields(vendor)
        body.append("# Field numbers, parsed from vendor/xla/pjrt/proto/compile_options.proto")
        body.append(f"PROTO_FIELDS = {pf!r}")
        body.append("")

        for name, vals in sorted(enums.items()):
            body.append(f"# enum {name}")
            for k, v in vals:
                body.append(f"{k} = {v}")
            body.append("")

        for r in toposort(records, known):
            if not r.fields:
                continue
            try:
                body.append(emit_record(r, known, sizes))
            except NotImplementedError as e:
                body.append(f"# SKIPPED {r.name}: {e}\n")

        mod.write_text("\n".join(body))
        print(f"wrote {mod}  ({len(fn_fields)} vtable slots, "
              f"{len(records)} records, {len(enums)} enums, "
              f"vtable_offset={vtable_off})")
        return 0
    finally:
        shim.unlink(missing_ok=True)


if __name__ == "__main__":
    raise SystemExit(main())
